name: hellow-world

on: push

jobs:
  hellow-world-job:

    runs-on: ubuntu-latest

    steps: 
      - name: check out repository code
        uses: actions/checkout@v6
      - run: echo "$(cat hello_world.txt)"
